In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [8]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,101,20) # start, end, step

array([  0,  20,  40,  60,  80, 100])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [31]:
len(np.linspace(0,10,21))

21

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(2,5) #[0,1)

array([[0.44460418, 0.84405603, 0.61777205, 0.29627249, 0.02766606],
       [0.90348665, 0.08606193, 0.92882311, 0.3561118 , 0.35988161]])

In [39]:
np.random.rand(5) #[0,1)

array([0.24105364, 0.75234463, 0.57007246, 0.14333418, 0.34059289])

In [40]:
np.random.randn(10)

array([-1.58456052, -0.69512943,  1.38275661, -1.94175549,  0.58719863,
       -1.0483458 , -0.84015359,  1.28379903, -0.69037719,  0.47372113])

In [42]:
np.random.randn(2,3)

array([[ 0.36168263,  0.29691078, -0.92039106],
       [-0.25553557, -0.69596285, -1.57793908]])

In [46]:
np.random.randint(10,15,4) #[parmeter1, parameter2)

array([14, 11, 14, 12])

In [49]:
np.random.randint(10,13,(4,5,4)) #[parmeter1, parameter2)

array([[[11, 12, 12, 12],
        [10, 10, 10, 10],
        [11, 11, 12, 10],
        [11, 10, 12, 10],
        [11, 10, 10, 12]],

       [[10, 11, 10, 10],
        [11, 12, 10, 10],
        [12, 12, 12, 11],
        [11, 10, 10, 12],
        [11, 11, 12, 12]],

       [[10, 11, 12, 11],
        [10, 10, 12, 10],
        [12, 12, 12, 12],
        [11, 10, 12, 12],
        [12, 12, 11, 11]],

       [[10, 12, 12, 12],
        [12, 11, 10, 12],
        [10, 11, 11, 10],
        [11, 12, 12, 10],
        [10, 10, 10, 10]]])

In [51]:
np.random.seed(101) 
np.random.rand(4) 

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [52]:
np.random.seed(101)  
np.random.rand(4) 

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [53]:
np.random.rand(4) 

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [54]:
np.random.rand(4) 

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [55]:
arr = np.arange(0,25)

In [59]:
arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.reshape(5,4) 

ValueError: ignored

In [61]:
ranarr = np.random.randint(0,101,10)

In [62]:
ranarr

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [63]:
ranarr.max()

83

In [64]:
ranarr.min()

8

In [65]:
ranarr.argmax() # Max value index

1

In [66]:
ranarr.argmin() # Min value index

2

In [67]:
ranarr.dtype

dtype('int64')

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr.shape

(25,)

In [70]:
arr = arr.reshape(5,5)

In [71]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
arr.shape

(5, 5)

In [74]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])